// Mocks generated by Mockito 5.4.6 from annotations
// in thelittlelibrary/test/data/auth/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:google_sign_in/google_sign_in.dart' as _i2;
import 'package:google_sign_in/src/event_types.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGoogleSignInAuthorizationClient_0 extends _i1.SmartFake
    implements _i2.GoogleSignInAuthorizationClient {
  _FakeGoogleSignInAuthorizationClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoogleSignInAccount_1 extends _i1.SmartFake
    implements _i2.GoogleSignInAccount {
  _FakeGoogleSignInAccount_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GoogleSignIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignIn extends _i1.Mock implements _i2.GoogleSignIn {
  @override
  _i3.Stream<_i4.GoogleSignInAuthenticationEvent> get authenticationEvents =>
      (super.noSuchMethod(
        Invocation.getter(#authenticationEvents),
        returnValue: _i3.Stream<_i4.GoogleSignInAuthenticationEvent>.empty(),
        returnValueForMissingStub:
            _i3.Stream<_i4.GoogleSignInAuthenticationEvent>.empty(),
      ) as _i3.Stream<_i4.GoogleSignInAuthenticationEvent>);

  @override
  _i2.GoogleSignInAuthorizationClient get authorizationClient =>
      (super.noSuchMethod(
        Invocation.getter(#authorizationClient),
        returnValue: _FakeGoogleSignInAuthorizationClient_0(
          this,
          Invocation.getter(#authorizationClient),
        ),
        returnValueForMissingStub: _FakeGoogleSignInAuthorizationClient_0(
          this,
          Invocation.getter(#authorizationClient),
        ),
      ) as _i2.GoogleSignInAuthorizationClient);

  @override
  _i3.Future<void> initialize({
    String? clientId,
    String? serverClientId,
    String? nonce,
    String? hostedDomain,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #clientId: clientId,
            #serverClientId: serverClientId,
            #nonce: nonce,
            #hostedDomain: hostedDomain,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i2.GoogleSignInAccount?>? attemptLightweightAuthentication(
          {bool? reportAllExceptions = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #attemptLightweightAuthentication,
          [],
          {#reportAllExceptions: reportAllExceptions},
        ),
        returnValueForMissingStub: null,
      ) as _i3.Future<_i2.GoogleSignInAccount?>?);

  @override
  bool supportsAuthenticate() => (super.noSuchMethod(
        Invocation.method(
          #supportsAuthenticate,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool authorizationRequiresUserInteraction() => (super.noSuchMethod(
        Invocation.method(
          #authorizationRequiresUserInteraction,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Future<_i2.GoogleSignInAccount> authenticate(
          {List<String>? scopeHint = const []}) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [],
          {#scopeHint: scopeHint},
        ),
        returnValue: _i3.Future<_i2.GoogleSignInAccount>.value(
            _FakeGoogleSignInAccount_1(
          this,
          Invocation.method(
            #authenticate,
            [],
            {#scopeHint: scopeHint},
          ),
        )),
        returnValueForMissingStub: _i3.Future<_i2.GoogleSignInAccount>.value(
            _FakeGoogleSignInAccount_1(
          this,
          Invocation.method(
            #authenticate,
            [],
            {#scopeHint: scopeHint},
          ),
        )),
      ) as _i3.Future<_i2.GoogleSignInAccount>);

  @override
  _i3.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
