// Mocks generated by Mockito 5.4.6 from annotations
// in thelittlelibrary/test/features/scanner/barcode/barcode_scanner_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:google_mlkit_barcode_scanning/src/barcode_scanner.dart' as _i2;
import 'package:google_mlkit_commons/google_mlkit_commons.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BarcodeScanner].
///
/// See the documentation for Mockito's code generation for more information.
class MockBarcodeScanner extends _i1.Mock implements _i2.BarcodeScanner {
  @override
  List<_i2.BarcodeFormat> get formats => (super.noSuchMethod(
        Invocation.getter(#formats),
        returnValue: <_i2.BarcodeFormat>[],
        returnValueForMissingStub: <_i2.BarcodeFormat>[],
      ) as List<_i2.BarcodeFormat>);

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  _i4.Future<List<_i2.Barcode>> processImage(_i5.InputImage? inputImage) =>
      (super.noSuchMethod(
        Invocation.method(
          #processImage,
          [inputImage],
        ),
        returnValue: _i4.Future<List<_i2.Barcode>>.value(<_i2.Barcode>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.Barcode>>.value(<_i2.Barcode>[]),
      ) as _i4.Future<List<_i2.Barcode>>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
